LPS-79348 SF
pavel-savinov/liferay-portal pull request #158
Opened 2018-04-10 12:16 UTC by ealonso

2018-04-10 12:17 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2018-04-10 13:39 UTC, pavel-savinov commented on modules/apps/web-experience/asset/asset-publisher-web/src/main/java/com/liferay/asset/publisher/web/util/AssetPublisherUtil.java
> +		return new BaseModelSearchResult<>(results, results.size());
Usage of `results.size()` here will always give us `(end - start - nonDisplayable)` number of entries, but not the total count as it was before.

2018-04-10 13:43 UTC, pavel-savinov requested changes
@arthurchan35 Could you please take a look at my comment? Also, as I can see, it comes from the Support and if you need any help with it please create an SME request and talk to @dacousalr. Thanks!

2018-04-10 13:43 UTC, closed without merging

2018-04-11 08:41 UTC, arthurchan35 commented
@pavel-savinov 
Thanks, I am seeing the issue you refered to. And I think I am going to sovle it before the result returned from index engine and service layer.